### ISSUE TITLE
GDPR changes

### ISSUE THREAD

**Issue by bennidhamma** [keepcosmos/terjira#71] opened 2019-04-16 22:46 UTC
It looks like the new GDPR changes in JIRA Cloud have broken username support. I am unable to authenticate with terjira. Any plans to fix?

Here's a ticket with more info about the problem over at another cli: 
https://bobswift.atlassian.net/projects/JCLI/issues/JCLI-1471

**Comment by ghosteathuman** [comment] 2020-06-29 23:34
Hi @bennidhamma I am not sure if you are still facing this issue? I am able to login to a Jira Cloud instance using terjira without much issue.

If this is still occurring for you, maybe you could detail down some reproduction steps with more information?

**Comment by kaganozupek** [comment] 2020-09-10 20:57
Maybe old but the problem is jira is not supporting basic authentication with password anymore. Just create an api token from jira and enter your api token instead of your password. @ghosteathuman maybe you consider to add this to Readme.

**Comment by ghosteathuman** [comment] 2020-09-12 06:46
@kaganozupek Thanks for the suggestion!

It's already documented in the README to use the API Token.
![Jira Login README](https://user-images.githubusercontent.com/46582963/92989372-85b40d80-f506-11ea-9b44-0d488b8dff2e.png)

Since on Atlassian end they made it explicit that they have deprecated passwords in basic auth, I don't feel the need to repeat that information here.

https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

**Comment by ghosteathuman** [comment] 2020-09-19 09:26
I am going to go ahead and close this ticket end of this month (Sept) if I didn't receive any response or feedback. From my day to day use, seems like there are no GDPR breaking changes for terjira.

@bennidhamma If you have any broken experience, feel free to comment on this ticket before that. If not, please create another issue then.

**Closed** 2020-10-04 06:34 UTC
